stages:
  - Lint
  - Unit Test
  - Build Test

jobs:
  - stage: Lint
    language: node_js
    sudo: false
    node_js:
      - 10
      - 9
    install:
      - npm install
    script:
      - npm run lint

  - stage: Unit Test
    language: node_js
    sudo: false
    node_js:
      - 10
      - 9
    install:
      - npm install
    script:
      - npm run test

  - stage: Build Test
    language: node_js
    sudo: false
    node_js:
      - 10
      - 9
    install:
      - npm install
    script:
      - npm run build