language: node_js
sudo: false
node_js:
  - 10
  - 9

jobs:
  include: 
  - stage: Code Linting
    install:
      - npm install
    script:
      - npm run lint
  - stage: Unit Tests
    install:
      - npm install
    script:
      - npm run test
  - stage: Build Test
    install:
      - npm install
    script:
      - npm run build
      